//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.20 at 05:11:21 PM PDT 
//


package com.datatorrent.alerts.conf.xmlbind;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.datatorrent.alerts.conf.xmlbind package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.datatorrent.alerts.conf.xmlbind
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Conf }
     * 
     */
    public Conf createConf() {
        return new Conf();
    }

    /**
     * Create an instance of {@link Conf.EmailContext }
     * 
     */
    public Conf.EmailContext createConfEmailContext() {
        return new Conf.EmailContext();
    }

    /**
     * Create an instance of {@link Conf.EmailRecipient }
     * 
     */
    public Conf.EmailRecipient createConfEmailRecipient() {
        return new Conf.EmailRecipient();
    }

    /**
     * Create an instance of {@link Conf.EmailMessage }
     * 
     */
    public Conf.EmailMessage createConfEmailMessage() {
        return new Conf.EmailMessage();
    }

    /**
     * Create an instance of {@link Conf.Criteria }
     * 
     */
    public Conf.Criteria createConfCriteria() {
        return new Conf.Criteria();
    }

}
